import type { ImageFactoryTemplate } from "../types";

/** 女装带货主线：平铺变模特 → 上身图 → 各类场景。 */
export const FASHION_TEMPLATES: ImageFactoryTemplate[] = [
  {
    id: "flat-to-model",
    name: "平铺变模特图",
    category: "服装",
    description: "把平铺图或挂拍图里的衣服穿到真人模特身上，场景可点选。",
    prompt: "生成一张写实的服装上身展示图。参考图里的服装是平铺图或挂拍图，把它自然地穿到真人模特身上。严格保持服装的颜色、图案、印花位置与比例、版型剪裁、领口袖型、门襟与口袋结构、面料质感和缝线细节完全不变；不要改色、不要重新设计款式、不要增删任何部件。提供模特参考图时，严格保持该模特的脸、发型、肤色和体型；没有提供模特参考图时，默认生成一位年轻的亚洲女性模特，五官自然、妆容清爽。服装必须贴合身体，肩线、腰线、垂坠与褶皱走向符合真实穿着的物理关系，光影方向与场景一致。画面中不出现文字、水印、品牌标识、价格与促销标签；不臆造参考图中没有的配饰；不要把多个视角拼进同一张图。只输出一张真实、可直接发布的成图，人物是画面主角，构图留出呼吸空间。",
    aspectRatio: "3:4",
    thumb: "flat-to-model",
    preview: "/template-previews/flat-to-model.jpg",
    slots: [
      { id: "garment", label: "服装平铺图", description: "平铺或挂拍的服装正面，尽量无遮挡", required: true },
      { id: "model", label: "模特参考", description: "可选，用于锁定模特的脸型、体型与气质", required: false, fromModelLibrary: true },
    ],
    scenePresets: [
      { id: "store-mannequin", label: "店内同款模特架", prompt: "服装店内，模特站在穿着同款服装的人体模特架旁，一手自然搭在模特架上整理衣服，眼神看向模特架，店内简约高级，暖色射灯。" },
      { id: "window-shot", label: "橱窗外拍摄", prompt: "模特站在时尚女装店铺的玻璃橱窗外，手持黑色单反相机对着橱窗内穿同款服装的白色人体模特拍摄，玻璃有自然反光，街道日光明亮。" },
      { id: "window-bookshelf", label: "窗边书架文艺", prompt: "室内落地窗边的木色书架旁，窗外是落叶街道与来往车辆，白色窗帘与花瓶点缀，光线柔和温暖，文艺轻奢风格。" },
      { id: "rainy-cafe", label: "雨天咖啡屋", prompt: "咖啡屋靠窗座位，窗外秋雨淅沥、街道湿润，桌上放着杂志与一束鲜花，模特侧坐看向镜头，氛围松弛温馨。" },
      { id: "easel-portrait", label: "画架自画像", prompt: "室内画室，模特一手持画笔一手托着调色盘，站在木质画架前作画，背景摆着画作与绿植，暖光，艺术氛围浓厚。" },
      { id: "autumn-ginkgo", label: "秋日银杏街道", prompt: "秋日街道旁，金黄银杏叶缀满枝头、落叶铺满地面，模特自然站姿看向镜头，色调温暖，氛围闲适惬意。" },
      { id: "winter-snow", label: "冬日雪景户外", prompt: "室外冬日雪景，树木与地面覆着白雪，远处是街道与建筑，模特面对镜头自然站立，光线明亮，空气感清冷。" },
      { id: "chinese-courtyard", label: "中式庭院", prompt: "中式庭院回廊，午后阳光洒进院内，金黄银杏与木质栏杆相映，模特手持团扇，姿态优雅闲适。" },
      { id: "night-balcony", label: "露台夜景", prompt: "城市露台边缘，夜幕下灯火阑珊、星空璀璨，暖光台灯与白玫瑰点缀，模特轻扶栏杆，浪漫文艺氛围。" },
      { id: "store-projection", label: "店内投影墙", prompt: "黑白轻奢装修的女装店内一角，墙面投影投射出同款穿搭的宣传画面，模特倚靠在收银台边，姿态松弛。" },
      { id: "casual-snapshot", label: "日常快照", prompt: "日常快照风格，非精心构图与打光，柔和自然光，模特坐在店内沙发上双腿交叉，随性松弛，抓拍感。" },
      { id: "with-pet", label: "与宠物同框", prompt: "室内窗边，模特身旁伴着一只白色小型犬或猫，窗外是街景，画面温馨自然，模特看向镜头微笑。" },
    ],
    builtIn: true,
  },
  {
    id: "model-tryon",
    name: "模特换装",
    category: "服装",
    description: "固定人物身份，把指定服装穿到模特身上。",
    prompt: "生成一张写实换装图。严格保持模特的脸、发型、肤色、体型和身体比例；严格保持服装的颜色、版型、图案、面料与结构。服装应自然贴合身体，遮挡、褶皱、手脚和光影关系真实。",
    aspectRatio: "3:4",
    thumb: "model-tryon",
    preview: "/template-previews/model-tryon.jpg",
    slots: [
      { id: "model", label: "模特图", description: "用于锁定人物身份和体型", required: true, fromModelLibrary: true },
      { id: "garment", label: "服装图", description: "要穿到模特身上的目标服装", required: true },
      { id: "style", label: "场景参考", description: "可选，用于确定背景和拍摄风格", required: false },
    ],
    scenePresets: [
      { id: "studio-plain", label: "纯色棚拍", prompt: "干净的浅灰或米色背景棚拍，柔和均匀的影棚光，人物居中站立，突出服装本身。" },
      { id: "boutique", label: "服装店内", prompt: "现代服装店内，衣架与展示柜环绕，暖色射灯，模特自然站立展示整体穿搭。" },
      { id: "window-light", label: "窗边自然光", prompt: "室内落地窗边，自然光从侧面洒入，白色窗帘与绿植点缀，光影柔和干净。" },
      { id: "city-street", label: "城市街拍", prompt: "都市街道平视拍摄，背景是街铺与虚化的行人，日常通勤感，光线自然。" },
      { id: "autumn-leaves", label: "秋日落叶", prompt: "秋日街道，金黄落叶铺满地面，暖调阳光穿过树梢，氛围闲适。" },
      { id: "snow-field", label: "冬日雪景", prompt: "户外冬日雪景，白雪覆盖树木与地面，光线明亮，空气感清冷。" },
      { id: "cafe-seat", label: "咖啡店", prompt: "咖啡店靠窗座位，木质桌面与咖啡器具，窗外是街景，松弛的日常感。" },
      { id: "blue-sky", label: "蓝天户外", prompt: "澄澈蓝天下的户外空地，上方有绿色枝叶垂落，轻微仰拍，清新明亮。" },
      { id: "home-corner", label: "居家角落", prompt: "温馨居家角落，米色墙面、布艺沙发与绿植，暖光，生活气息浓。" },
      { id: "night-street", label: "夜晚街道", prompt: "夜晚城市街道，商铺灯光与路灯光斑作背景，情绪安静，人像中景。" },
    ],
    builtIn: true,
  },
  {
    id: "mirror-selfie",
    name: "对镜自拍",
    category: "服装",
    description: "模特在全身镜前手机自拍，最像真人日常发的穿搭图。",
    prompt: "生成一张真实的对镜自拍图。模特站在全身镜或落地镜前用手机自拍，画面是镜子里的映像。严格保持参考图中服装的颜色、图案、版型、面料质感与所有细节完全不变；提供模特参考图时保持其脸、发型、肤色和体型，没有提供时默认生成一位年轻的亚洲女性模特。手机可以自然遮挡部分面部，手臂与手机的角度符合真实自拍的物理关系，镜面反射与室内光线一致。竖版构图，完整展示整体穿搭。画面中不出现文字、水印、品牌标识与促销标签，不臆造参考图中没有的配饰。只输出一张真实、可直接发布的成图。",
    aspectRatio: "3:4",
    thumb: "mirror-selfie",
    preview: "/template-previews/mirror-selfie.jpg",
    slots: [
      { id: "look", label: "模特上身图", description: "模特穿着目标服装的照片，也可直接传服装平铺图", required: true },
      { id: "style", label: "场景参考", description: "可选，用于确定镜子样式与室内风格", required: false },
    ],
    scenePresets: [
      { id: "store-mirror", label: "服装店落地镜", prompt: "现代服装店内的落地镜旁，店内亮堂大气，模特手拿手机全身自拍，竖版构图展现整体穿搭。" },
      { id: "bedroom-mirror", label: "居家卧室镜", prompt: "居家卧室角落的黑色细边落地镜，背景是床与床头柜、暖色台灯，黑米木色调，简约现代。" },
      { id: "french-interior", label: "法式轻奢室内", prompt: "法式轻奢风室内，米白色素净墙面，角落有复古花瓶与插花，柔和暖光，模特站在镜前自拍。" },
      { id: "elevator", label: "电梯轿厢", prompt: "电梯轿厢内的镜面，银色金属面板与楼层按键，浅灰纹理地板，光线明亮柔和。" },
      { id: "arch-mirror", label: "拱形全身镜", prompt: "室内黑色极窄边框的拱形全身镜前，左侧有复古雕花壁炉，壁炉上摆着杂志与小摆件。" },
      { id: "rainy-window", label: "雨天窗边", prompt: "室内窗边，大面积玻璃窗上布满雨滴，窗外是雨天街道与行驶车辆，大理石桌面与绿植点缀。" },
      { id: "phone-cover-face", label: "手机挡脸", prompt: "模特手持手机挡住半张脸自拍，另一只手叉腰展示穿搭，姿态随性自然，重点在整体搭配。" },
      { id: "mirror-back", label: "背对镜中同框", prompt: "模特背对镜头站在镜前，镜子里映出正面身影，前景有鲜花点缀，窗外是雪景街道。" },
      { id: "rack-wall", label: "高端衣架墙", prompt: "高端服装店内，黑白棕色调，黑色金属衣架挂满服装，后方大面积镜面墙延伸空间感。" },
      { id: "shop-glass", label: "街边玻璃窗", prompt: "街边玻璃橱窗前，模特举着手机对着玻璃反射自拍，神情自然，手里提着购物袋。" },
      { id: "white-frame-mirror", label: "白框细边镜", prompt: "居家场景，椭圆形白色金属细边镜，浅色墙面、绿植与花束、浅棕沙发和木地板。" },
      { id: "projection-wall", label: "投影星空墙", prompt: "现代简约室内，浅灰墙面上投影着星空银河，模特用手机遮住半张脸，姿态松弛。" },
    ],
    builtIn: true,
  },
  {
    id: "storefront",
    name: "门店场景",
    category: "服装",
    description: "店内、店门口、咖啡屋等有陈设的商业空间穿搭图。",
    prompt: "生成一张真实的门店场景穿搭图。模特在服装店内或店门口自然活动。严格保持参考图中服装的颜色、图案、版型、面料质感与所有细节完全不变；提供模特参考图时保持其脸、发型、肤色和体型，没有提供时默认生成一位年轻的亚洲女性模特。店内陈设、光线与人物身上的光影方向保持一致，人物是画面主角，陈设不喧宾夺主。画面中不出现可辨认的真实品牌名称、店招文字、价格牌与促销标签，也不要水印，不臆造参考图中没有的配饰。只输出一张真实、可直接发布的成图。",
    aspectRatio: "3:4",
    thumb: "storefront",
    preview: "/template-previews/storefront.jpg",
    slots: [
      { id: "look", label: "模特上身图", description: "模特穿着目标服装的照片，也可直接传服装平铺图", required: true },
      { id: "style", label: "场景参考", description: "可选，用于确定门店风格与陈设", required: false },
    ],
    scenePresets: [
      { id: "luxe-shelf", label: "轻奢店内货架", prompt: "室内轻奢风，浅色架子上摆着精致物品与花艺，窗外是傍晚的冬日雪景街道与摩天轮。" },
      { id: "black-stairs", label: "店内黑楼梯", prompt: "装饰着黑色杂志架与黑白摆件的店内，有一段黑色楼梯，窗外秋雨濛濛、黄叶满树。" },
      { id: "sofa-corner", label: "沙发休息区", prompt: "店内灰色皮沙发，模特坐着看向镜头，左侧杂志架摆满时尚杂志，木质小架子上有摆件。" },
      { id: "autumn-cafe", label: "咖啡屋秋雨", prompt: "治愈系咖啡屋，窗外秋雨淅沥、秋叶泛黄，屋内有咖啡器具、相机与鲜花，慵懒松弛。" },
      { id: "vintage-books", label: "复古书店", prompt: "复古书店的书架之间，暖黄灯光照亮书脊与衣角，堆叠的木箱与绿植，文艺复古氛围。" },
      { id: "white-shelf", label: "白色置物架", prompt: "明亮白色系店内，白色置物架上摆着手提包、绿植与装饰画，落地窗外是冬日雪景。" },
      { id: "poster-wall", label: "店内海报墙", prompt: "店内深色置物架前挂着一幅大型人物海报，海报上是同款穿搭，旁边陈列着手提包与花艺。" },
      { id: "bench-outside", label: "店门口长凳", prompt: "橱窗外的米白色长凳，模特翘腿坐着手拿咖啡，旁边有白色小柜与绿植。" },
      { id: "old-street", label: "老街青石板", prompt: "青石板老街上，模特目光看向街边的复古橱窗，脚步自然迈出，背景是老街铺面。" },
      { id: "terrace-cafe", label: "露天咖啡座", prompt: "户外咖啡馆的露天座位，桌上放着咖啡与甜点，背景是来往行人与暖黄灯光。" },
      { id: "door-steps", label: "门口台阶", prompt: "店门口的台阶旁立着金色边框海报，海报上的人物与模特同款穿搭，模特站姿优雅。" },
      { id: "rainy-mall-street", label: "雨天商业街", prompt: "下雨的商业街，行人打着伞赶路，街道湿润，模特坐在咖啡店外看向镜头。" },
      { id: "rattan-chair", label: "藤椅复古角", prompt: "复古藤椅上双腿交叠，身后木质货架陈列着复古衣物，窗边绿植的光影洒在地面。" },
    ],
    builtIn: true,
  },
  {
    id: "outdoor-street",
    name: "户外街拍",
    category: "服装",
    description: "雪景、蓝天、街道、车内等户外与出行场景。",
    prompt: "生成一张真实的户外街拍穿搭图。严格保持参考图中服装的颜色、图案、版型、面料质感与所有细节完全不变；提供模特参考图时保持其脸、发型、肤色和体型，没有提供时默认生成一位年轻的亚洲女性模特。环境光线与季节要和服装厚薄相匹配，人物与背景的透视、景深自然，衣服的垂坠与风感真实。画面中不出现文字、水印、可辨认的品牌标识与车牌，不臆造参考图中没有的配饰。只输出一张真实、可直接发布的成图，人物是画面主角。",
    aspectRatio: "3:4",
    thumb: "outdoor-street",
    preview: "/template-previews/outdoor-street.jpg",
    slots: [
      { id: "look", label: "模特上身图", description: "模特穿着目标服装的照片，也可直接传服装平铺图", required: true },
      { id: "style", label: "场景参考", description: "可选，用于确定环境与季节氛围", required: false },
    ],
    scenePresets: [
      { id: "snow-hold", label: "雪地捧雪", prompt: "冬日雪景，树木与灌木覆着白雪，空中飘着雪花，绿色铁艺围栏，模特双手捧起一团雪，清冷唯美。" },
      { id: "cafe-bench-snow", label: "咖啡店外长椅", prompt: "冬季雪天，模特坐在咖啡店外的木质长椅上，长椅上放着精致小包与一束花，手持咖啡杯看向镜头。" },
      { id: "sky-lowangle", label: "蓝天仰拍", prompt: "澄澈湛蓝的天空，上方垂落翠绿树叶枝桠，模特站在浅灰色石质平台上，轻微仰拍，清新明亮。" },
      { id: "low-wall", label: "白色矮墙", prompt: "模特坐在白色矮墙边缘，背景是蓝天白云，左侧有翠绿树叶垂落，色调清新明亮。" },
      { id: "spring-street", label: "春日绿意街道", prompt: "带绿树、浅色围墙与街道设施的绿意街道，阳光明媚的春日感，暖调光线，完整展示全身穿搭。" },
      { id: "park-bench", label: "公园长椅阅读", prompt: "公园的木质长椅，模特双手捧着一本翻开的书，头微低注视书页，周围树木成荫。" },
      { id: "chinese-garden", label: "中式园林", prompt: "户外中式园林，模特倚靠在木质栏杆上，背景是回廊与绿植，光影自然通透。" },
      { id: "dappled-light", label: "斑驳树影", prompt: "阳光明媚的白天，茂密树木与低矮灌木错落，光影透过树叶在地面形成斑驳光斑，浅棕色建筑墙体作背景。" },
      { id: "urban-eyelevel", label: "都市街景平视", prompt: "平视角度拍摄的都市街景，镜头距离适中，背景是街铺与建筑，人物与街景同样清晰。" },
      { id: "fallen-leaves", label: "秋日落叶街", prompt: "秋日街道，金黄落叶铺地、枝头黄叶满树，模特自然站立或迈步，整体暖色调。" },
      { id: "in-car-day", label: "车内街景", prompt: "车内视角，透过车窗能看到清新的街景绿意，长发被风吹起，光影落在头发与脸上，日常松弛。" },
      { id: "in-car-night", label: "雨夜车内", prompt: "夜晚雨天的车内，窗外是城市街道、路灯与行驶的车辆，暗调光线，氛围安静。" },
      { id: "beside-suv", label: "越野车旁", prompt: "模特侧身倚靠在深色越野车旁，双手插兜，姿态随性，背景是开阔的户外场地。" },
    ],
    builtIn: true,
  },
  {
    id: "portrait-studio",
    name: "人像写真",
    category: "服装",
    description: "偏摄影质感的人像，含展厅、海报同框等强氛围场景。",
    prompt: "生成一张有摄影质感的人像写真。严格保持参考图中服装的颜色、图案、版型、面料质感与所有细节完全不变；提供模特参考图时保持其脸、发型、肤色和体型，没有提供时默认生成一位年轻的亚洲女性模特。光线、景深与情绪都为人物服务，肤色自然不过度磨皮，构图取中景或全身并留出呼吸空间。画面中不出现文字、水印、品牌标识与促销标签，不臆造参考图中没有的配饰。只输出一张真实、可直接发布的成图。",
    aspectRatio: "3:4",
    thumb: "portrait-studio",
    preview: "/template-previews/portrait-studio.jpg",
    slots: [
      { id: "look", label: "模特上身图", description: "模特穿着目标服装的照片，也可直接传服装平铺图", required: true },
      { id: "style", label: "风格参考", description: "可选，用于确定摄影风格与色调", required: false },
    ],
    scenePresets: [
      { id: "white-gallery", label: "白色艺术展厅", prompt: "简约的白色艺术展厅，模特站在自己的大幅人像海报旁，墙面干净、射灯打亮，艺术展陈氛围。" },
      { id: "giant-poster", label: "巨幅肖像同框", prompt: "模特侧身站立、头微抬望向墙面的巨幅个人肖像海报，海报中的人物与她同款穿搭。" },
      { id: "unfinished-portrait", label: "画室未完成肖像", prompt: "靠窗的温馨室内，白砖墙旁立着木质画架，画架上是一幅未完成的肖像画，小圆桌上有玫瑰与咖啡。" },
      { id: "projection-look", label: "投影墙同款", prompt: "现代室内，墙面投影投射出与模特同款穿搭的画面，黑色台面与射灯，时尚展示感。" },
      { id: "billboard-street", label: "商业街巨型海报", prompt: "繁华商业街区，模特与自己的巨型广告海报趣味同框，背景是现代玻璃建筑与往来行人。" },
      { id: "ginkgo-forest", label: "银杏树林", prompt: "一片金黄的银杏树林，树叶浓郁金黄、地面铺满落叶，秋日温暖明媚，自然光通透。" },
      { id: "night-city", label: "夜晚城市街道", prompt: "夜晚城市街道，背景有亮灯的商铺、行驶车辆与路灯光斑，人像中景，情绪安静。" },
      { id: "backlit-sunset", label: "逆光夕阳快照", prompt: "日常快照风格，无精心构图与打光，逆光夕阳，头发微微凌乱，真实的皮肤质感。" },
      { id: "film-grain", label: "胶片电影感", prompt: "电影质感的胶片摄影，朦胧诗意、带自然颗粒感，柔和光线，专业人像摄影风格。" },
      { id: "pink-blossom", label: "粉花树下", prompt: "开满粉色花朵的树旁，背景是绿植与黄花灌木丛，春日明媚，表情灵动自然。" },
      { id: "stool-cat", label: "高脚凳抱猫", prompt: "现代空间内，模特坐在高脚凳上怀抱一只长毛猫，黑色台面与暖光，优雅温柔。" },
      { id: "curved-stairs", label: "弧形楼梯", prompt: "模特站在室内的弧形楼梯上，手里拿着几朵鲜花，妆容精致，眼神看向镜头，从容自信。" },
      { id: "ccd-clean", label: "CCD 清新风", prompt: "CCD 相机质感的人像摄影，夏日清新与极简风融合，画面明亮干净，氛围唯美。" },
    ],
    builtIn: true,
  },
];
